import { Jost, Dosis } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/Themes/themeProvider";

const jost = Jost({
  variable: '--font-jost',
  subsets: ['latin']
})

const dosis = Dosis({
  variable: '--font-dosis',
  subsets: ['latin']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body
        className={`${dosis.variable} ${jost.variable} font-[dosis] antialiased scroll-smooth`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

          <main className="relative z-40 min-h-screen">
            {children}
          </main>

        </ThemeProvider>
      </body>
    </html>
  );
}
